### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by codehangen** [hasii2011/gittodoistclone#43]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by hasii2011** [comment]
Thanks for the comment.  

Yes, it is.  

Currently, I am hung up on the rewrite of the UI on [Pyut](https://github.com/hasii2011/PyUt).  However, I missed an internal milestone for updating to [TODOIST new API](https://github.com/hasii2011/gittodoistclone/issues/42) and doing a [new release for the M1 Macs](https://github.com/hasii2011/gittodoistclone/issues/41)

What kind of help are you offering?

**Comment by hasii2011** [comment]
Great!!  Anxious to hear what we could do for documentation.  I have an [issue](https://github.com/hasii2011/gittodoistclone/issues/40) we could use directly or just repurpose.

By translation, I am assuming you are talking about the application itself

**Comment by hasii2011** [comment]
Another couple of questions?

What is your interest in this project?  Why this one?  How did you find it?

**Comment by hasii2011** [comment]
How do you propose we get started with the updated documentation?
